excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://SilvioLuis.github.io
name: Rodovidas
description: My awesome new site
author: Silvio Luis
avatar: http://www.gravatar.com/avatar/48628a58fbfea91077c83bb432ccdbcf?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 